language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
addons:
  apt:
    update: true
install:
  - pip install pip==20.2.3
  - pip install -r requirements.txt -U
before_script:
  - ./analyse-source-code.sh
notifications:
  email: false
